# Generated by Django 3.2.9 on 2021-12-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product_sum',
        ),
    ]
