# Generated by Django 3.2.9 on 2021-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211207_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
